name: finding
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  motion_tab_bar_v2: ^0.3.0
  google_maps_flutter: ^2.2.0
  location: ^5.0.0
  intl: ^0.20.0
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  map_picker: ^0.0.3
  smooth_page_indicator: ^1.0.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.0.13
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
